meta_name: "Farmland"
meta_title: "Farmland - Shop local, share a ride, save the planet !"
meta_description: "Get your farm-fresh products directly from local farms, even if you don't have a car. Carpool, reduce your CO2 emissions and enjoy the best local produce !"
meta_image: "farmland_cover.png"
twitter_account: "@sebasfourn"
